-- 53-softball-and-tennis-showcases.sql
--
-- Two sources checked in 52, added in full.
--
-- SOFTBALL: College Softball Prospects' College Coaches Showcase Camps, 30
-- events from 17 October to 21 November 2026. Each event page names its own
-- five to seven programs, read 2026-09-14. $219 for one session, $319 for two,
-- $419 for three, and every page caps the ratio at 8 players per coach. Park
-- City was already in the table from 52 and is a no-op here. Program names are
-- lightly normalised the same way as 51 ("California State University,
-- Bakersfield" is Cal State Bakersfield) so a school reads the same everywhere.
-- Sewell, NJ lives at sewell-nj_.cfm, underscore and all; that is the real URL.
--
-- TENNIS: eleven UTR Sports college camps from utrsports.net/pages/college-camps,
-- 7 November 2026 to 3 January 2027, each hosted at one university. As with
-- Indiana and Methodist in 52, the host is the program named. Each camp page
-- sits behind a UTR sign-in, so the link is the public college-camps list
-- instead, and cost is left null because only the sign-in page shows it.
-- Multi-day camps are one row on their first day, the catalogue's existing
-- convention; the eligibility note carries the full dates.
--
-- Deliberately not added from the same UTR list: "Fourth Annual ONE DAY (Girls)
-- - UTR Sports and USTA FL Girls Clinic at UNF" (a USTA Florida girls' clinic,
-- not a recruiting camp) and Inspiration Academy's weekly camps (an academy,
-- not a college).

insert into camps
  (school, camp_name, division, region, cost, eligibility, registration_status,
   city, state, date, type, source_url, sport, verified_at, attending_programs)
values
  ('College Coaches Showcase Camps', 'Newberg College Coaches Showcase', 'Showcase', 'West', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Newberg', 'OR', '2026-10-17'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/newberg-or.cfm', 'softball-women', '2026-09-14'::date,
   array['Cal State Bakersfield', 'Cal State Fullerton', 'George Fox University', 'Idaho State University', 'Portland State University']),
  ('College Coaches Showcase Camps', 'Park City College Coaches Showcase', 'Showcase', 'West', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Park City', 'UT', '2026-10-17'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/park-city-ut.cfm', 'softball-women', '2026-09-14'::date,
   array['Cal State Bakersfield', 'Cal State Fullerton', 'Idaho State University', 'University of Utah', 'Utah State University']),
  ('College Coaches Showcase Camps', 'Auburn College Coaches Showcase', 'Showcase', 'West', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Auburn', 'WA', '2026-10-18'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/auburn-wa.cfm', 'softball-women', '2026-09-14'::date,
   array['Cal State Bakersfield', 'Cal State Fullerton', 'Idaho State University', 'Lewis and Clark College', 'Pacific Lutheran University', 'Portland State University']),
  ('College Coaches Showcase Camps', 'Bellevue College Coaches Showcase', 'Showcase', 'Midwest', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Bellevue', 'NE', '2026-10-18'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/bellevue-ne.cfm', 'softball-women', '2026-09-14'::date,
   array['Creighton University', 'Iowa State University', 'Jacksonville State University', 'University of Missouri-Kansas City', 'University of Northern Iowa', 'University of South Dakota']),
  ('College Coaches Showcase Camps', 'Jacksonville College Coaches Showcase', 'Showcase', 'Southeast', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Jacksonville', 'AL', '2026-10-18'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/jacksonville-al.cfm', 'softball-women', '2026-09-14'::date,
   array['Jacksonville State University', 'Kennesaw State University', 'Lipscomb University', 'University of North Alabama', 'University of Tennessee Chattanooga']),
  ('College Coaches Showcase Camps', 'Wauwatosa College Coaches Showcase', 'Showcase', 'Midwest', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Wauwatosa', 'WI', '2026-10-18'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/wauwatosa-wi.cfm', 'softball-women', '2026-09-14'::date,
   array['Colorado School of Mines', 'Northern Illinois University', 'University of Northern Iowa', 'University of Notre Dame', 'University of Wisconsin', 'Wisconsin Lutheran College']),
  ('College Coaches Showcase Camps', 'Fullerton College Coaches Showcase', 'Showcase', 'West', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Fullerton', 'CA', '2026-10-24'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/fullerton-ca.cfm', 'softball-women', '2026-09-14'::date,
   array['Cal State Fullerton', 'Cal State Bakersfield', 'Concordia University Irvine', 'Fullerton College', 'The University of Texas at Arlington', 'University of California, Riverside']),
  ('College Coaches Showcase Camps', 'Niagara University College Coaches Showcase', 'Showcase', 'Northeast', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Niagara University', 'NY', '2026-10-24'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/niagara-university-ny.cfm', 'softball-women', '2026-09-14'::date,
   array['Binghamton University', 'Canisius University', 'Niagara University', 'St. Bonaventure University', 'University at Buffalo']),
  ('College Coaches Showcase Camps', 'Saint Paul College Coaches Showcase', 'Showcase', 'Midwest', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Saint Paul', 'MN', '2026-10-24'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/saint-paul-mn.cfm', 'softball-women', '2026-09-14'::date,
   array['Idaho State University', 'Macalester College', 'University of Minnesota', 'University of North Dakota', 'University of Northern Iowa']),
  ('College Coaches Showcase Camps', 'Carmichael College Coaches Showcase', 'Showcase', 'West', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Carmichael', 'CA', '2026-10-25'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/carmichael-ca.cfm', 'softball-women', '2026-09-14'::date,
   array['American River College', 'Cal State Bakersfield', 'Sacramento State', 'Jessup University', 'University of the Pacific', 'The University of Texas at Arlington']),
  ('College Coaches Showcase Camps', 'Lakewood College Coaches Showcase', 'Showcase', 'Mountain', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Lakewood', 'CO', '2026-10-25'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/lakewood-co.cfm', 'softball-women', '2026-09-14'::date,
   array['Cal State Fullerton', 'Colorado Christian University', 'Colorado State University', 'Regis University', 'University of Northern Colorado']),
  ('College Coaches Showcase Camps', 'Manassas College Coaches Showcase', 'Showcase', 'Mid-Atlantic', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Manassas', 'VA', '2026-10-25'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/manassas-va.cfm', 'softball-women', '2026-09-14'::date,
   array['George Mason University', 'Indiana University of Pennsylvania', 'Queens University of Charlotte', 'Towson University', 'University of Maryland, Baltimore County', 'University of Virginia']),
  ('College Coaches Showcase Camps', 'Rochester College Coaches Showcase', 'Showcase', 'Midwest', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Rochester', 'MI', '2026-10-25'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/rochester-mi.cfm', 'softball-women', '2026-09-14'::date,
   array['Ball State University', 'Oakland University', 'St. Bonaventure University', 'University of Detroit Mercy', 'University of Notre Dame', 'University of Toledo']),
  ('College Coaches Showcase Camps', 'Beech Grove College Coaches Showcase', 'Showcase', 'Midwest', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Beech Grove', 'IN', '2026-10-31'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/beech-grove-in.cfm', 'softball-women', '2026-09-14'::date,
   array['Bowling Green State University', 'Northern Kentucky University', 'University of Evansville', 'University of Notre Dame', 'Ball State University']),
  ('College Coaches Showcase Camps', 'Spring College Coaches Showcase', 'Showcase', 'South Central', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Spring', 'TX', '2026-10-31'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/spring-tx.cfm', 'softball-women', '2026-09-14'::date,
   array['Lamar University', 'Sam Houston State University', 'Southeastern Louisiana University', 'St. Edward''s University', 'The University of Texas at Austin', 'University of Kansas']),
  ('College Coaches Showcase Camps', 'Westerville College Coaches Showcase', 'Showcase', 'Midwest', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Westerville', 'OH', '2026-10-31'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/westerville-oh.cfm', 'softball-women', '2026-09-14'::date,
   array['Bowling Green State University', 'Otterbein University', 'Ohio University', 'The University of Akron', 'Youngstown State University']),
  ('College Coaches Showcase Camps', 'River Forest College Coaches Showcase', 'Showcase', 'Midwest', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'River Forest', 'IL', '2026-11-01'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/river-forest-il.cfm', 'softball-women', '2026-09-14'::date,
   array['Concordia University Chicago', 'DePaul University', 'Northern Illinois University', 'University of Illinois at Chicago', 'University of Northern Iowa', 'University of Notre Dame']),
  ('College Coaches Showcase Camps', 'Decatur College Coaches Showcase', 'Showcase', 'Southeast', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Decatur', 'GA', '2026-11-07'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/decatur-ga.cfm', 'softball-women', '2026-09-14'::date,
   array['Auburn University at Montgomery', 'Georgia Institute of Technology', 'Georgia State University', 'Kennesaw State University', 'Mercer University']),
  ('College Coaches Showcase Camps', 'Jersey City College Coaches Showcase', 'Showcase', 'Northeast', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Jersey City', 'NJ', '2026-11-07'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/jersey-city-nj.cfm', 'softball-women', '2026-09-14'::date,
   array['Monmouth University', 'Rutgers University', 'Saint Peter''s University', 'Stony Brook University', 'Wagner College', 'Quinnipiac University']),
  ('College Coaches Showcase Camps', 'Plano College Coaches Showcase', 'Showcase', 'South Central', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Plano', 'TX', '2026-11-07'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/plano-tx.cfm', 'softball-women', '2026-09-14'::date,
   array['East Texas A&M University', 'Lamar University', 'Northwestern State University', 'The University of Texas at Austin', 'University of Tulsa']),
  ('College Coaches Showcase Camps', 'Sewell College Coaches Showcase', 'Showcase', 'Northeast', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Sewell', 'NJ', '2026-11-08'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/sewell-nj_.cfm', 'softball-women', '2026-09-14'::date,
   array['Binghamton University', 'Lafayette College', 'Lehigh University', 'Rutgers University', 'Stony Brook University']),
  ('College Coaches Showcase Camps', 'Smyrna College Coaches Showcase', 'Showcase', 'Southeast', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Smyrna', 'TN', '2026-11-08'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/smyrna-tn.cfm', 'softball-women', '2026-09-14'::date,
   array['Austin Peay State University', 'Belmont University', 'Kennesaw State University', 'University of Tennessee at Martin', 'University of West Georgia']),
  ('College Coaches Showcase Camps', 'St. Louis College Coaches Showcase', 'Showcase', 'Midwest', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'St. Louis', 'MO', '2026-11-08'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/st-louis-mo.cfm', 'softball-women', '2026-09-14'::date,
   array['Maryville University', 'Southern Illinois University Edwardsville', 'University of Evansville', 'University of Kansas', 'University of Northern Iowa']),
  ('College Coaches Showcase Camps', 'Charlotte College Coaches Showcase', 'Showcase', 'Southeast', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Charlotte', 'NC', '2026-11-14'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/charlotte-nc.cfm', 'softball-women', '2026-09-14'::date,
   array['Appalachian State University', 'Campbell University', 'Kennesaw State University', 'Queens University of Charlotte', 'The University of North Carolina at Chapel Hill']),
  ('College Coaches Showcase Camps', 'Louisville College Coaches Showcase', 'Showcase', 'Southeast', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Louisville', 'KY', '2026-11-15'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/louisville-ky.cfm', 'softball-women', '2026-09-14'::date,
   array['Bellarmine University', 'Belmont University', 'Marshall University', 'University of Evansville', 'University of Louisville']),
  ('College Coaches Showcase Camps', 'Milton College Coaches Showcase', 'Showcase', 'Northeast', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Milton', 'MA', '2026-11-15'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/milton-ma.cfm', 'softball-women', '2026-09-14'::date,
   array['Boston College', 'Bryant University', 'Fairfield University', 'Rutgers University', 'University of Maine', 'University of Maryland, Baltimore County']),
  ('College Coaches Showcase Camps', 'Edmond College Coaches Showcase', 'Showcase', 'South Central', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Edmond', 'OK', '2026-11-21'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/edmond-ok.cfm', 'softball-women', '2026-09-14'::date,
   array['Harding University', 'Oklahoma Christian University', 'University of Central Arkansas', 'University of Kansas', 'University of Tulsa']),
  ('College Coaches Showcase Camps', 'Glendale College Coaches Showcase', 'Showcase', 'West', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Glendale', 'AZ', '2026-11-21'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/glendale-az.cfm', 'softball-women', '2026-09-14'::date,
   array['Arizona Christian University', 'Arizona State University', 'Cal State Fullerton', 'Cal State Bakersfield', 'Grand Canyon University', 'New Mexico State University', 'University of Arizona']),
  ('College Coaches Showcase Camps', 'Lakeland College Coaches Showcase', 'Showcase', 'Southeast', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Lakeland', 'FL', '2026-11-21'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/lakeland-fl.cfm', 'softball-women', '2026-09-14'::date,
   array['Georgia State University', 'Rutgers University', 'Southeastern University', 'Stetson University', 'University of Central Florida', 'University of North Florida']),
  ('College Coaches Showcase Camps', 'Natchitoches College Coaches Showcase', 'Showcase', 'Southeast', 219,
   'High school players; $219 one session, $319 two, $419 three; max 8 players per coach', 'Open',
   'Natchitoches', 'LA', '2026-11-21'::date, 'Open Exposure / Showcase',
   'https://www.collegesoftballprospects.com/natchitoches-la.cfm', 'softball-women', '2026-09-14'::date,
   array['Lamar University', 'Louisiana Tech University', 'McNeese State University', 'Nicholls State University', 'Northwestern State University']),
  ('Pfeiffer University', 'UTR Sports College Camp', 'NCAA D3 host', 'Southeast', null,
   'Junior players; Nov 7-8; verify age and UTR', 'Open', 'Misenheimer', 'NC', '2026-11-07'::date,
   'Open Exposure / Showcase', 'https://www.utrsports.net/pages/college-camps', 'tennis-coed', '2026-09-14'::date,
   array['Pfeiffer University']),
  ('Texas Tech University', 'UTR Sports College Camp', 'NCAA D1 host', 'South Central', null,
   'Junior players; Nov 19-20; verify age and UTR', 'Open', 'Lubbock', 'TX', '2026-11-19'::date,
   'Open Exposure / Showcase', 'https://www.utrsports.net/pages/college-camps', 'tennis-coed', '2026-09-14'::date,
   array['Texas Tech University']),
  ('Arizona State University', 'UTR Sports College Camp', 'NCAA D1 host', 'West', null,
   'Junior players; Nov 20-21; verify age and UTR', 'Open', 'Tempe', 'AZ', '2026-11-20'::date,
   'Open Exposure / Showcase', 'https://www.utrsports.net/pages/college-camps', 'tennis-coed', '2026-09-14'::date,
   array['Arizona State University']),
  ('TCU', 'UTR Sports College Camp', 'NCAA D1 host', 'South Central', null,
   'Junior players; Nov 27-29; verify age and UTR', 'Open', 'Fort Worth', 'TX', '2026-11-27'::date,
   'Open Exposure / Showcase', 'https://www.utrsports.net/pages/college-camps', 'tennis-coed', '2026-09-14'::date,
   array['TCU']),
  ('TCU', 'UTR Sports College Camp', 'NCAA D1 host', 'South Central', null,
   'Junior players; Dec 4-6; verify age and UTR', 'Open', 'Fort Worth', 'TX', '2026-12-04'::date,
   'Open Exposure / Showcase', 'https://www.utrsports.net/pages/college-camps', 'tennis-coed', '2026-09-14'::date,
   array['TCU']),
  ('TCU', 'UTR Sports College Camp', 'NCAA D1 host', 'South Central', null,
   'Junior players; Dec 11-13; verify age and UTR', 'Open', 'Fort Worth', 'TX', '2026-12-11'::date,
   'Open Exposure / Showcase', 'https://www.utrsports.net/pages/college-camps', 'tennis-coed', '2026-09-14'::date,
   array['TCU']),
  ('Samford University', 'UTR Sports College Camp', 'NCAA D1 host', 'Southeast', null,
   'Junior players; Dec 12-13; verify age and UTR', 'Open', 'Birmingham', 'AL', '2026-12-12'::date,
   'Open Exposure / Showcase', 'https://www.utrsports.net/pages/college-camps', 'tennis-coed', '2026-09-14'::date,
   array['Samford University']),
  ('West Virginia University', 'UTR Sports College Camp', 'NCAA D1 host', 'Mid-Atlantic', null,
   'Junior players; Dec 12-13; verify age and UTR', 'Open', 'Morgantown', 'WV', '2026-12-12'::date,
   'Open Exposure / Showcase', 'https://www.utrsports.net/pages/college-camps', 'tennis-coed', '2026-09-14'::date,
   array['West Virginia University']),
  ('Auburn University', 'UTR Sports College Camp', 'NCAA D1 host', 'Southeast', null,
   'Junior players; Dec 19-20; verify age and UTR', 'Open', 'Auburn', 'AL', '2026-12-19'::date,
   'Open Exposure / Showcase', 'https://www.utrsports.net/pages/college-camps', 'tennis-coed', '2026-09-14'::date,
   array['Auburn University']),
  ('Baylor University', 'UTR Sports College Winter Tennis Camp', 'NCAA D1 host', 'South Central', null,
   'Junior players; Dec 26-27, with Baylor head coach Joey Scrivano; verify age and UTR', 'Open', 'Waco', 'TX', '2026-12-26'::date,
   'Open Exposure / Showcase', 'https://www.utrsports.net/pages/college-camps', 'tennis-coed', '2026-09-14'::date,
   array['Baylor University']),
  ('Harvard University', 'UTR Sports College Camp', 'NCAA D1 host', 'Northeast', null,
   'Junior players; Jan 2-3, indoor; verify age and UTR', 'Open', 'Cambridge', 'MA', '2027-01-02'::date,
   'Open Exposure / Showcase', 'https://www.utrsports.net/pages/college-camps', 'tennis-coed', '2026-09-14'::date,
   array['Harvard University'])
on conflict do nothing;

-- Expect softball_showcases = 30 and tennis_college_camps = 13 (these 11 plus
-- Indiana and Methodist).
select
  (select count(*) from camps
    where school = 'College Coaches Showcase Camps' and cardinality(attending_programs) > 0) as softball_showcases,
  (select count(*) from camps
    where sport = 'tennis-coed' and camp_name like 'UTR Sports College%'
      and cardinality(attending_programs) > 0 and date >= current_date) as tennis_college_camps;
