// Recruiting questionnaire links — national starter set.
//
// Standalone rather than attached to College Finder rows: this file names
// schools officially ("University of South Alabama") while college-data.js
// uses short names, and the two don't reconcile cleanly enough to attach a
// link without risking the wrong school's form. So these live in their own
// searchable finder keyed by nothing but themselves.
//
// Source: hand-verified lists, publish=TRUE + Verified, updated 2026-08-06.
// Shape: [school, state, level, gender, sport, url]. state is a 2-letter code,
// gender is Men | Women | Both. Add rows for new sports the same way.

export const QUESTIONNAIRES = [
  ["Allegany College of Maryland","MD","JUCO","Both","Basketball","https://acmtrojans.com/sb_output.aspx?form=3"],
  ["Canisius University","NY","D1","Men","Basketball","https://gogriffs.com/sb_output.aspx?form=6"],
  ["Central Maine Community College","ME","JUCO","Men","Basketball","https://www.cmmustangs.com/information/recruiting/mbkb_recruit"],
  ["Dakota State University","SD","NAIA","Men","Basketball","https://dsuathletics.com/sb_output.aspx?form=6"],
  ["Daytona State College","FL","JUCO","Women","Basketball","https://dscfalcons.com/sports/wbkb/RecruIt_Questionnaire"],
  ["Delaware State University","DE","D1","Men","Basketball","https://questionnaires.armssoftware.com/a8afdc2bf465"],
  ["Dominican University New York","NY","D2","Men","Basketball","https://questionnaires.armssoftware.com/b6891d1e43a2"],
  ["East Georgia State College","GA","JUCO","Both","Basketball","https://www.ega.edu/athletics/recruit-questionnaire.html"],
  ["Eastern University","PA","D3","Men","Basketball","https://goeasterneagles.com/sb_output.aspx?frform=3&path=mbball"],
  ["Florida Institute of Technology","FL","D2","Men","Basketball","https://floridatechsports.com/sb_output.aspx?form=40"],
  ["Florida State College at Jacksonville","FL","JUCO","Men","Basketball","https://fscjmantarays.com/sports/mbkb/questionnaire"],
  ["Garden City Community College","KS","JUCO","Men","Basketball","https://www.gobroncbusters.com/information/mbkb-recuriting"],
  ["Georgia Institute of Technology","GA","D1","Both","Basketball","https://ramblinwreck.com/student-athlete-questionnaire/"],
  ["Georgia State University","GA","D1","Men","Basketball","https://college.jumpforward.com/questionnaire.aspx?iid=564&sportid=15"],
  ["Georgia State University","GA","D1","Women","Basketball","https://georgiastatesports.com/news/2008/11/1/3731625.aspx"],
  ["Grand Rapids Community College","MI","JUCO","Men","Basketball","https://grccraiders.com/sb_output.aspx?form=21"],
  ["Hamline University","MN","D3","Men","Basketball","https://hamlineathletics.com/sb_output.aspx?frform=2"],
  ["Hawai'i Pacific University","HI","D2","Both","Basketball","https://hpusharks.com/sb_output.aspx?form=3"],
  ["Illinois Institute of Technology","IL","D3","Both","Basketball","https://illinoistechathletics.com/sports/2023/7/13/recruit-form.aspx"],
  ["Illinois State University","IL","D1","Women","Basketball","https://college.jumpforward.com/questionnaire.aspx?iid=354&sportid=3"],
  ["Illinois Wesleyan University","IL","D3","Men","Basketball","https://www.iwusports.com/sb_output.aspx?frform=1"],
  ["Indiana State University","IN","D1","Men","Basketball","https://gosycamores.com/sb_output.aspx?form=14"],
  ["Indiana University Bloomington","IN","D1","Women","Basketball","https://college.jumpforward.com/questionnaire.aspx?iid=436&sportid=3"],
  ["Indiana University South Bend","IN","NAIA","Both","Basketball","https://iusbtitans.com/sb_output.aspx?form=6"],
  ["Indiana University Southeast","IN","NAIA","Both","Basketball","https://iusathletics.com/sb_output.aspx?form=3"],
  ["IU Indianapolis","IN","D1","Men","Basketball","https://questionnaires.armssoftware.com/1e2ec3958a81"],
  ["Kansas City Kansas Community College","KS","JUCO","Men","Basketball","https://bluedevils.kckcc.edu/sports/mbkb/recruiting_questionnaire"],
  ["Kentucky State University","KY","D2","Both","Basketball","https://ksuthorobreds.com/sb_output.aspx?form=3"],
  ["Lake Michigan College","MI","JUCO","Men","Basketball","https://redhawks.lakemichigancollege.edu/sports/mbkb/Men-s_basketball_recruit_form"],
  ["Louisiana Tech University","LA","D1","Women","Basketball","https://latechsports.com/sports/2018/7/20/ot-recruiting-questionnaires-html"],
  ["Maine Maritime Academy","ME","D3","Men","Basketball","https://questionnaires.armssoftware.com/5f0f295037b5"],
  ["Massachusetts College of Liberal Arts","MA","D3","Men","Basketball","https://athletics.mcla.edu/sports/mbkb/Recruit_Me"],
  ["Massachusetts Institute of Technology","MA","D3","Men","Basketball","https://questionnaires.armssoftware.com/307fecfb9396"],
  ["Mercy University","NY","D2","Both","Basketball","https://mercyathletics.com/sb_output.aspx?form=7"],
  ["Michigan Technological University","MI","D2","Men","Basketball","https://questionnaires.armssoftware.com/1f0f9b481572"],
  ["Minnesota State University Mankato","MN","D2","Men","Basketball","https://questionnaires.armssoftware.com/6b36740adf92"],
  ["Mississippi State University","MS","D1","Men","Basketball","https://hailstate.com/form/9"],
  ["Mississippi State University","MS","D1","Women","Basketball","https://hailstate.com/form/2042"],
  ["Missouri Southern State University","MO","D2","Men","Basketball","https://questionnaires.armssoftware.com/3ed47a00a1b6"],
  ["Montana State University","MT","D1","Men","Basketball","https://questionnaires.armssoftware.com/9f932dabdd0b"],
  ["Montana State University Billings","MT","D2","Men","Basketball","https://msubsports.com/sb_output.aspx?form=18"],
  ["Montana State University Northern","MT","NAIA","Both","Basketball","https://golightsgo.com/sb_output.aspx?form=3"],
  ["New Jersey Institute of Technology","NJ","D1","Men","Basketball","https://questionnaires.armssoftware.com/3cb1c79fc8d0"],
  ["New Mexico State University","NM","D1","Men","Basketball","https://nmstatesports.com/sb_output.aspx?form=22"],
  ["North Carolina State University","NC","D1","Both","Basketball","https://gopack.com/sports/2015/4/27/GEN_20140101185"],
  ["North Carolina Wesleyan University","NC","D3","Both","Basketball","https://ncwsports.com/sports/2024/7/19/prospective-student-athlete-questionnaire-forms.aspx"],
  ["North Dakota State University","ND","D1","Men","Basketball","https://questionnaires.armssoftware.com/d9b8c21c0ead"],
  ["Northern Illinois University","IL","D1","Men","Basketball","https://questionnaires.armssoftware.com/9accef2bda60"],
  ["Northern Oklahoma College","OK","JUCO","Both","Basketball","https://www.nocmavs.com/recruits"],
  ["Ohio Christian University","OH","NAIA","Both","Basketball","https://ocutrailblazers.com/sports/2023/9/13/recruiting-questionnaires.aspx"],
  ["Regis College","MA","D3","Men","Basketball","https://www.goregispride.com/sports/mbkb/Recruit_Questionnaire"],
  ["Rhodes College","TN","D3","Men","Basketball","https://rhodeslynx.com/sb_output.aspx?form=6&path=mbball"],
  ["Rowan College of South Jersey","NJ","JUCO","Both","Basketball","https://www.dukesathletics.com/Recruits/questionnaire"],
  ["South Carolina State University","SC","D1","Men","Basketball","https://my.armssoftware.com/arms/public/questionnaire/d428372a19c3"],
  ["South Carolina State University","SC","D1","Women","Basketball","https://my.armssoftware.com/arms/public/questionnaire/4cf99266ad6f"],
  ["Southeast Missouri State University","MO","D1","Men","Basketball","https://college.jumpforward.com/questionnaire.aspx?iid=315&sportid=15"],
  ["Southeastern Louisiana University","LA","D1","Men","Basketball","https://questionnaires.armssoftware.com/080d49de4a1a"],
  ["Southern Arkansas University","AR","D2","Men","Basketball","https://muleriderathletics.com/sb_output.aspx?form=10"],
  ["Southern New Hampshire University","NH","D2","Both","Basketball","https://snhupenmen.com/sports/2021/5/5/information-PSA-questionnaires-index"],
  ["Tennessee Technological University","TN","D1","Both","Basketball","https://www.ttusports.com/be_a_golden_eagle/questionnaire_page"],
  ["Texas A&M University","TX","D1","Both","Basketball","https://12thman.com/news/2011/08/04/prospective-athlete-questionnaire"],
  ["Texas Wesleyan University","TX","NAIA","Men","Basketball","https://ramsports.net/sb_output.aspx?form=7"],
  ["Thomas Jefferson University","PA","D2","Men","Basketball","https://jeffersonrams.com/sb_output.aspx?form=7"],
  ["Union College","NY","D3","Men","Basketball","https://questionnaires.armssoftware.com/1d274cb1dc08"],
  ["University of Alabama in Huntsville","AL","D2","Men","Basketball","https://uahchargers.com/sb_output.aspx?form=5"],
  ["University of Alaska Fairbanks","AK","D2","Men","Basketball","https://alaskananooks.com/sb_output.aspx?form=5"],
  ["University of Alaska Fairbanks","AK","D2","Women","Basketball","https://questionnaires.armssoftware.com/428bd553cc26"],
  ["University of Arkansas at Monticello","AR","D2","Men","Basketball","https://www.uamsports.com/sb_output.aspx?form=27"],
  ["University of Arkansas at Pine Bluff","AR","D1","Both","Basketball","https://uapblionsroar.com/sb_output.aspx?form=1"],
  ["University of Central Arkansas","AR","D1","Men","Basketball","https://questionnaires.armssoftware.com/f3520c867103"],
  ["University of Central Florida","FL","D1","Men","Basketball","https://college.jumpforward.com/questionnaire.aspx?iid=382&path=mbball&sportid=15"],
  ["University of Central Oklahoma","OK","D2","Men","Basketball","https://questionnaires.armssoftware.com/ba4f9cb5c69b"],
  ["University of Connecticut","CT","D1","Both","Basketball","https://uconnhuskies.com/form/3"],
  ["University of Delaware","DE","D1","Both","Basketball","https://www1.udel.edu/forms/sportsinfo/"],
  ["University of Hawai'i at Hilo","HI","D2","Men","Basketball","https://questionnaires.armssoftware.com/3a40af83cb1a"],
  ["University of Kansas","KS","D1","Women","Basketball","https://questionnaires.armssoftware.com/e27bc4305342"],
  ["University of Kentucky","KY","D1","Both","Basketball","https://ukathletics.com/recruits/"],
  ["University of Louisiana Monroe","LA","D1","Men","Basketball","https://ulmwarhawks.com/sb_output.aspx?form=6"],
  ["University of Maine at Augusta","ME","USCAA","Both","Basketball","https://www.umamoose.com/information/Recruiting_questionaire/basketball_questionnaire"],
  ["University of Maine at Farmington","ME","D3","Men","Basketball","https://goumfbeavers.com/sports/2022/5/9/information-forms-recruiting-mens-basketball.aspx"],
  ["University of Maryland, College Park","MD","D1","Both","Basketball","https://umterps.com/form/5"],
  ["University of Maryland, College Park","MD","D1","Men","Basketball","https://questionnaires.armssoftware.com/637b2b6f576e"],
  ["University of Massachusetts Amherst","MA","D1","Both","Basketball","https://umassathletics.com/form/3"],
  ["University of Massachusetts Boston","MA","D3","Men","Basketball","https://beaconsathletics.com/sb_output.aspx?form=9"],
  ["University of Michigan-Dearborn","MI","NAIA","Both","Basketball","https://athletics.umdearborn.edu/information/recruiting"],
  ["University of Minnesota Crookston","MN","D2","Men","Basketball","https://questionnaires.armssoftware.com/5834ab4b585d"],
  ["University of Minnesota Morris","MN","NAIA","Both","Basketball","https://admissions.morris.umn.edu/register/RecruitQuestionnaire"],
  ["University of Nebraska at Kearney","NE","D2","Both","Basketball","https://lopers.com/sb_output.aspx?form=4"],
  ["University of Nebraska-Lincoln","NE","D1","Men","Basketball","https://questionnaires.armssoftware.com/e6b75ca567a7"],
  ["University of Nevada, Reno","NV","D1","Both","Basketball","https://nevadawolfpack.com/sb_output.aspx?form=6"],
  ["University of Nevada, Reno","NV","D1","Women","Basketball","https://questionnaires.armssoftware.com/3f419f551a8e"],
  ["University of New England","ME","D3","Men","Basketball","https://athletics.une.edu/sb_output.aspx?form=29&path=mbball"],
  ["University of New Hampshire","NH","D1","Both","Basketball","https://unhwildcats.com/sports/2020/6/19/prospective-student-athlete-questionnaires"],
  ["University of New Hampshire","NH","D1","Men","Basketball","https://questionnaires.armssoftware.com/113c1085775c"],
  ["University of North Carolina Asheville","NC","D1","Men","Basketball","https://questionnaires.armssoftware.com/ae7cd96f3678"],
  ["University of Northern Iowa","IA","D1","Men","Basketball","https://college.jumpforward.com/questionnaire.aspx?iid=537&sportid=15"],
  ["University of Northwestern Ohio","OH","NAIA","Both","Basketball","https://www.unoh.edu/athletics/recruit-questionnaire/"],
  ["University of Rhode Island","RI","D1","Both","Basketball","https://gorhody.com/sports/2020/6/9/information-psa-questionnaires.aspx"],
  ["University of Rhode Island","RI","D1","Women","Basketball","https://questionnaires.armssoftware.com/58324baf0ee4"],
  ["University of South Alabama","AL","D1","Women","Basketball","https://questionnaires.armssoftware.com/c83498187260"],
  ["University of South Carolina","SC","D1","Both","Basketball","https://gamecocksonline.com/news/2018/06/21/ot-recruiting-questionnaires-html/"],
  ["University of South Carolina Aiken","SC","D2","Both","Basketball","https://pacersports.com/sb_output.aspx?form=3"],
  ["University of South Dakota","SD","D1","Men","Basketball","https://college.jumpforward.com/questionnaire.aspx?iid=453&sportid=15"],
  ["University of Texas at Dallas","TX","D3","Both","Basketball","https://utdcomets.com/sb_output.aspx?form=3"],
  ["University of Texas at Dallas","TX","D3","Men","Basketball","https://questionnaires.armssoftware.com/bcc3263f7612"],
  ["University of Texas at San Antonio","TX","D1","Both","Basketball","https://goutsa.com/prospective-student-athletes-questionnaires"],
  ["University of Vermont","VT","D1","Men","Basketball","https://questionnaires.armssoftware.com/a4faa3edaa60"],
  ["University of Wisconsin-Green Bay","WI","D1","Men","Basketball","https://greenbayphoenix.com/sb_output.aspx?form=5"],
  ["Virginia Polytechnic Institute and State University","VA","D1","Men","Basketball","https://college.jumpforward.com/questionnaire.aspx?iid=472&sportid=15"],
  ["Wagner College","NY","D1","Men","Basketball","https://wagnerathletics.com/sb_output.aspx?form=26"],
  ["Western Connecticut State University","CT","D3","Men","Basketball","https://westconnathletics.com/sb_output.aspx?form=18"],
  ["Western Illinois University","IL","D1","Both","Basketball","https://goleathernecks.com/sb_output.aspx?form=3"],
  ["Western Oklahoma State College","OK","JUCO","Men","Basketball","https://pioneers.wosc.edu/sports/mbkb/recruiting_form"],
  ["WVU Potomac State College","WV","JUCO","Men","Basketball","https://www.potomacstatesports.com/recruits/mbasketball-recruits"],
  ["Xavier University of Louisiana","LA","NAIA","Both","Basketball","https://xulagold.com/sports/2019/3/20/recruiting-questionnaires"],
  ["Arizona State University","AZ","D1","Men","Football","https://questionnaires.armssoftware.com/ab20d3134f9f"],
  ["Austin Peay State University","TN","D1","Men","Football","https://letsgopeay.com/sb_output.aspx?form=24"],
  ["Central Michigan University","MI","D1","Men","Football","https://questionnaires.armssoftware.com/6b6c8f52db3f"],
  ["Colorado Mesa University","CO","D2","Men","Football","https://cmumavericks.com/sb_output.aspx?form=2"],
  ["Delaware State University","DE","D1","Men","Football","https://questionnaires.armssoftware.com/d50b35477ad7"],
  ["Eastern Kentucky University","KY","D1","Men","Football","https://college.jumpforward.com/questionnaire.aspx?iid=1637&sportid=54"],
  ["Florida Atlantic University","FL","D1","Men","Football","https://questionnaires.armssoftware.com/4f0d0d975c59"],
  ["Indiana University Bloomington","IN","D1","Men","Football","https://questionnaires.armssoftware.com/ee805559225c"],
  ["Kansas State University","KS","D1","Men","Football","https://questionnaires.armssoftware.com/8fd884a36fbc"],
  ["Louisiana Tech University","LA","D1","Men","Football","https://questionnaires.armssoftware.com/ae17badbf668"],
  ["Mercer University","GA","D1","Men","Football","https://college.jumpforward.com/questionnaire.aspx?iid=500&sportid=54"],
  ["Minnesota State University, Mankato","MN","D2","Men","Football","https://questionnaires.armssoftware.com/cbe67caed9e3"],
  ["Missouri University of Science and Technology","MO","D2","Men","Football","https://questionnaires.armssoftware.com/7db0d273d7d8"],
  ["Monmouth University","NJ","D1","Men","Football","https://questionnaires.armssoftware.com/91eeff38abfc"],
  ["Nichols College","MA","D3","Men","Football","https://slate.nichols.edu/register/footballrecruitment"],
  ["North Carolina State University","NC","D1","Men","Football","https://questionnaires.armssoftware.com/fa5122606469"],
  ["North Dakota State University","ND","D1","Men","Football","https://questionnaires.armssoftware.com/8f1dc9c11e14"],
  ["Norwich University","VT","D3","Men","Football","https://connect.norwich.edu/register/athlete"],
  ["Ohio University","OH","D1","Men","Football","https://questionnaires.armssoftware.com/233a2d93ee59"],
  ["Plymouth State University","NH","D3","Men","Football","https://athletics.plymouth.edu/sports/2020/8/6/football-front-rush-recruit-form.aspx"],
  ["South Carolina State University","SC","D1","Men","Football","https://questionnaires.armssoftware.com/d8ebb8308ef1"],
  ["Union College","NY","D3","Men","Football","https://questionnaires.armssoftware.com/42d8e6235983"],
  ["University of Arkansas","AR","D1","Men","Football","https://questionnaires.armssoftware.com/567edf1eacb2"],
  ["University of California, Los Angeles","CA","D1","Men","Football","https://questionnaires.armssoftware.com/74c822368ab9"],
  ["University of Central Oklahoma","OK","D2","Men","Football","https://questionnaires.armssoftware.com/4e64987dd835"],
  ["University of Connecticut","CT","D1","Men","Football","https://questionnaires.armssoftware.com/a34f74e9b093"],
  ["University of Hawai'i at Mānoa","HI","D1","Men","Football","https://questionnaires.armssoftware.com/79737af39e0a"],
  ["University of Idaho","ID","D1","Men","Football","https://questionnaires.armssoftware.com/2a7618939f4f"],
  ["University of Illinois Urbana-Champaign","IL","D1","Men","Football","https://questionnaires.armssoftware.com/5c988717357b"],
  ["University of Maine","ME","D1","Men","Football","https://questionnaires.armssoftware.com/66a51f31ef1b"],
  ["University of Maryland, College Park","MD","D1","Men","Football","https://questionnaires.armssoftware.com/b37f2f0aac44"],
  ["University of Montana","MT","D1","Men","Football","https://questionnaires.armssoftware.com/b0fb10cd0c64"],
  ["University of Nebraska-Lincoln","NE","D1","Men","Football","https://questionnaires.armssoftware.com/d388bb15000c"],
  ["University of Nevada, Reno","NV","D1","Men","Football","https://questionnaires.armssoftware.com/6f8b6c2472a1"],
  ["University of New Mexico","NM","D1","Men","Football","https://questionnaires.armssoftware.com/fc6335185ee7"],
  ["University of Northern Iowa","IA","D1","Men","Football","https://college.jumpforward.com/questionnaire.aspx?iid=537&sportid=54"],
  ["University of Oregon","OR","D1","Men","Football","https://college.jumpforward.com/questionnaire.aspx?iid=510&sportid=18"],
  ["University of Pennsylvania","PA","D1","Men","Football","https://questionnaires.armssoftware.com/a8e4bf5dd078"],
  ["University of Puget Sound","WA","D3","Men","Football","https://admission.pugetsound.edu/register/loggerfootball"],
  ["University of Rhode Island","RI","D1","Men","Football","https://questionnaires.armssoftware.com/cfa3d431c131"],
  ["University of South Alabama","AL","D1","Men","Football","https://questionnaires.armssoftware.com/d043922d4bc0"],
  ["University of South Dakota","SD","D1","Men","Football","https://college.jumpforward.com/questionnaire.aspx?iid=453&sportid=54"],
  ["University of Southern Mississippi","MS","D1","Men","Football","https://questionnaires.armssoftware.com/8714178713d4"],
  ["University of Texas at El Paso","TX","D1","Men","Football","https://college.jumpforward.com/questionnaire.aspx?iid=396&sportid=54"],
  ["University of Utah","UT","D1","Men","Football","https://questionnaires.armssoftware.com/c15fb5f63631"],
  ["University of Virginia","VA","D1","Men","Football","https://questionnaires.armssoftware.com/5eb2b0c4eed7"],
  ["University of Wisconsin","WI","D1","Men","Football","https://questionnaires.armssoftware.com/73384a600a7f"],
  ["University of Wyoming","WY","D1","Men","Football","https://college.jumpforward.com/questionnaire.aspx?iid=556&sportid=54"],
  ["West Virginia Wesleyan College","WV","D2","Men","Football","https://bobcats.wvwc.edu/"],
  ["Arizona State University","AZ","D1","Women","Soccer","https://questionnaires.armssoftware.com/da2cc671ee6a"],
  ["Baker University","KS","NAIA","Men","Soccer","https://www.fieldlevel.com/bakeru/soccermen/recruiting"],
  ["Boise State University","ID","D1","Women","Soccer","https://questionnaires.armssoftware.com/b27d8322eb94"],
  ["Central Connecticut State University","CT","D1","Men","Soccer","https://www.fieldlevel.com/ccsu/soccermen/recruiting"],
  ["Central Wyoming College","WY","JUCO","Men","Soccer","https://www.fieldlevel.com/k4tr4dj4/soccermen/recruiting"],
  ["College of Southern Nevada","NV","JUCO","Men","Soccer","https://www.fieldlevel.com/csn/soccermen/recruiting"],
  ["Colorado State University Pueblo","CO","D2","Women","Soccer","https://questionnaires.armssoftware.com/d4aed0b1c2cd"],
  ["Dakota Wesleyan University","SD","NAIA","Men","Soccer","https://www.dwu.edu/Form-Mens-Soccer-Questionnaire"],
  ["East Mississippi Community College","MS","JUCO","Men","Soccer","https://www.fieldlevel.com/pynjrecy/soccermen/recruiting"],
  ["Florida State University","FL","D1","Women","Soccer","https://www.fieldlevel.com/fsu/soccerwomen/recruiting"],
  ["Fordham University","NY","D1","Men","Soccer","https://www.fieldlevel.com/fordham/soccermen/recruiting"],
  ["Georgia Southern University","GA","D1","Women","Soccer","https://questionnaires.armssoftware.com/c6e5fb83dbce"],
  ["Grand Canyon University","AZ","D1","Men","Soccer","https://www.fieldlevel.com/gcu/soccermen/recruiting"],
  ["Indiana University","IN","D1","Women","Soccer","https://college.jumpforward.com/questionnaire.aspx?iid=436&sportid=9"],
  ["Louisiana State University","LA","D1","Women","Soccer","https://www.fieldlevel.com/lsu/soccerwomen/recruiting"],
  ["Middle Georgia State University","GA","NAIA","Men","Soccer","https://www.fieldlevel.com/mgc/soccermen/recruiting"],
  ["Mississippi State University","MS","D1","Women","Soccer","https://www.fieldlevel.com/msstate/soccerwomen/recruiting"],
  ["Missouri State University","MO","D1","Men","Soccer","https://www.fieldlevel.com/missouristate/soccermen/recruiting"],
  ["Montana State University - Billings","MT","D2","Men","Soccer","https://www.fieldlevel.com/msubillings/soccermen/recruiting"],
  ["New Jersey Institute of Technology","NJ","D1","Women","Soccer","https://questionnaires.armssoftware.com/a533ccf4606f"],
  ["North Dakota State College of Science","ND","JUCO","Men","Soccer","https://www.fieldlevel.com/mt7arpn4/soccermen/recruiting"],
  ["North Dakota State University","ND","D1","Women","Soccer","https://questionnaires.armssoftware.com/c56ae03b6138"],
  ["Northwest Nazarene University","ID","D2","Men","Soccer","https://www.fieldlevel.com/nnu/soccermen/recruiting"],
  ["Oakland University","MI","D1","Men","Soccer","https://www.fieldlevel.com/oakland/soccermen/recruiting"],
  ["Ohio Northern University","OH","D3","Men","Soccer","https://www.fieldlevel.com/onu/soccermen/recruiting"],
  ["Oklahoma Wesleyan University","OK","NAIA","Men","Soccer","https://www.fieldlevel.com/okwu/soccermen/recruiting"],
  ["Oregon State University","OR","D1","Women","Soccer","https://osubeavers.com/sports/2012/3/19/208343622"],
  ["Penn State University","PA","D1","Women","Soccer","https://questionnaires.armssoftware.com/97bcf0e0d537"],
  ["Rhode Island College","RI","D3","Men","Soccer","https://www.fieldlevel.com/2jz2czrm/soccermen/recruiting"],
  ["Seattle University","WA","D1","Men","Soccer","https://www.fieldlevel.com/seattleu/soccermen/recruiting"],
  ["South Dakota State University","SD","D1","Women","Soccer","https://www.fieldlevel.com/sdstate/soccerwomen/recruiting"],
  ["Southern Maine Community College","ME","USCAA","Men","Soccer","https://www.fieldlevel.com/gvm8gz8i/soccermen/recruiting"],
  ["Southern Virginia University","VA","D3","Men","Soccer","https://www.fieldlevel.com/svu/soccermen/recruiting"],
  ["The College of New Jersey","NJ","D3","Men","Soccer","https://www.fieldlevel.com/cj76kx7w/soccermen/recruiting"],
  ["UNC - Wilmington","NC","D1","Men","Soccer","https://www.fieldlevel.com/uncw/soccermen/recruiting"],
  ["University at Buffalo","NY","D1","Women","Soccer","https://www.fieldlevel.com/buffalo/soccerwomen/recruiting"],
  ["University of Alabama at Birmingham","AL","D1","Men","Soccer","https://www.fieldlevel.com/uab/soccermen/recruiting"],
  ["University of Alabama at Birmingham","AL","D1","Women","Soccer","https://uabsports.com/form/25"],
  ["University of Arkansas at Little Rock","AR","D1","Women","Soccer","https://questionnaires.armssoftware.com/93ee67900e7a"],
  ["University of California - Davis","CA","D1","Men","Soccer","https://www.fieldlevel.com/ucdavis/soccermen/recruiting"],
  ["University of Central Arkansas","AR","D1","Men","Soccer","https://www.fieldlevel.com/uca/soccermen/recruiting"],
  ["University of Cincinnati","OH","D1","Women","Soccer","https://college.jumpforward.com/questionnaire.aspx?iid=379&sportid=9"],
  ["University of Connecticut","CT","D1","Women","Soccer","https://www.fieldlevel.com/uconn/soccerwomen/recruiting"],
  ["University of Delaware","DE","D1","Men","Soccer","https://www.fieldlevel.com/udel/soccermen/recruiting"],
  ["University of Delaware","DE","D1","Women","Soccer","https://www.fieldlevel.com/udel/soccerwomen/recruiting"],
  ["University of Denver","CO","D1","Men","Soccer","https://www.fieldlevel.com/du/soccermen/recruiting"],
  ["University of Hawaii at Hilo","HI","D2","Men","Soccer","https://www.fieldlevel.com/hawaii/soccermen/recruiting"],
  ["University of Hawaii at Hilo","HI","D2","Women","Soccer","https://questionnaires.armssoftware.com/c89532dbdb4e"],
  ["University of Illinois","IL","D1","Women","Soccer","https://www.fieldlevel.com/illinois/soccerwomen/recruiting"],
  ["University of Illinois at Chicago","IL","D1","Men","Soccer","https://www.fieldlevel.com/uic/soccermen/recruiting"],
  ["University of Iowa","IA","D1","Women","Soccer","https://questionnaires.armssoftware.com/407d9084738d"],
  ["University of Kansas","KS","D1","Women","Soccer","https://www.fieldlevel.com/ku/soccerwomen/recruiting"],
  ["University of Kentucky","KY","D1","Men","Soccer","https://www.fieldlevel.com/uky/soccermen/recruiting"],
  ["University of Kentucky","KY","D1","Women","Soccer","https://www.fieldlevel.com/uky/soccerwomen/recruiting"],
  ["University of Maine at Augusta","ME","USCAA","Women","Soccer","https://www.umamoose.com/information/Recruiting_questionaire/Recruit_Me_Page"],
  ["University of Maryland - Baltimore County","MD","D1","Men","Soccer","https://www.fieldlevel.com/umbc/soccermen/recruiting"],
  ["University of Maryland Baltimore County","MD","D1","Women","Soccer","https://www.fieldlevel.com/umbc/soccerwomen/recruiting"],
  ["University of Massachusetts - Amherst","MA","D1","Men","Soccer","https://www.fieldlevel.com/umass/soccermen/recruiting"],
  ["University of Massachusetts Amherst","MA","D1","Women","Soccer","https://questionnaires.armssoftware.com/2014c82d78a3"],
  ["University of Memphis","TN","D1","Men","Soccer","https://www.fieldlevel.com/memphis/soccermen/recruiting"],
  ["University of Michigan","MI","D1","Women","Soccer","https://questionnaires.armssoftware.com/88f3355d2c08"],
  ["University of Minnesota","MN","D1","Women","Soccer","https://questionnaires.armssoftware.com/eb86872cd989"],
  ["University of Minnesota Morris","MN","D3","Men","Soccer","https://www.fieldlevel.com/y9j3c9c9/soccermen/recruiting"],
  ["University of Missouri","MO","D1","Women","Soccer","https://questionnaires.armssoftware.com/d01925a6d474"],
  ["University of Montana","MT","D1","Women","Soccer","https://questionnaires.armssoftware.com/dfa8ed5216ba"],
  ["University of Nebraska","NE","D1","Women","Soccer","https://www.fieldlevel.com/nebraska/soccerwomen/recruiting"],
  ["University of Nebraska - Omaha","NE","D1","Men","Soccer","https://www.fieldlevel.com/unomaha/soccermen/recruiting"],
  ["University of Nevada, Reno","NV","D1","Women","Soccer","https://www.fieldlevel.com/unr/soccerwomen/recruiting"],
  ["University of New Hampshire","NH","D1","Men","Soccer","https://www.fieldlevel.com/crcrdkn9/soccermen/recruiting"],
  ["University of New Hampshire","NH","D1","Women","Soccer","https://www.fieldlevel.com/crcrdkn9/soccerwomen/recruiting"],
  ["University of New Mexico","NM","D1","Men","Soccer","https://www.fieldlevel.com/unm/soccermen/recruiting"],
  ["University of New Mexico","NM","D1","Women","Soccer","https://college.jumpforward.com/questionnaire.aspx?iid=425&sportid=9"],
  ["University of North Carolina Wilmington","NC","D1","Women","Soccer","https://questionnaires.armssoftware.com/c9e62a233300"],
  ["University of Oklahoma","OK","D1","Women","Soccer","https://questionnaires.armssoftware.com/7e68c39c0af8?path=soc"],
  ["University of Pennsylvania","PA","D1","Men","Soccer","https://www.fieldlevel.com/upenn/soccermen/recruiting"],
  ["University of Portland","OR","D1","Men","Soccer","https://www.fieldlevel.com/up/soccermen/recruiting"],
  ["University of Rhode Island","RI","D1","Women","Soccer","https://questionnaires.armssoftware.com/ca0cd10f36d1"],
  ["University of South Carolina","SC","D1","Men","Soccer","https://www.fieldlevel.com/sc/soccermen/recruiting"],
  ["University of South Carolina Upstate","SC","D1","Women","Soccer","https://questionnaires.armssoftware.com/75f92081a4ba"],
  ["University of South Florida","FL","D1","Men","Soccer","https://www.fieldlevel.com/ke2crij9/soccermen/recruiting"],
  ["University of Southern California","CA","D1","Women","Soccer","https://questionnaires.armssoftware.com/8527ea4d131d"],
  ["University of Southern Indiana","IN","D1","Men","Soccer","https://www.fieldlevel.com/usi/soccermen/recruiting"],
  ["University of Tennessee","TN","D1","Women","Soccer","https://questionnaires.armssoftware.com/1d56b54c82e9"],
  ["University of Texas - Tyler","TX","D2","Men","Soccer","https://www.fieldlevel.com/rkppqtch/soccermen/recruiting"],
  ["University of Texas at Austin","TX","D1","Women","Soccer","https://www.fieldlevel.com/texas/soccerwomen/recruiting"],
  ["University of Utah","UT","D1","Women","Soccer","https://questionnaires.armssoftware.com/c14f1ff0ed47"],
  ["University of Washington","WA","D1","Women","Soccer","https://questionnaires.armssoftware.com/70bc0c6c87f5"],
  ["University of Wisconsin","WI","D1","Men","Soccer","https://www.fieldlevel.com/wisconsin/soccermen/recruiting"],
  ["University of Wisconsin","WI","D1","Women","Soccer","https://questionnaires.armssoftware.com/9be4ddacfb6f"],
  ["University of Wyoming","WY","D1","Women","Soccer","https://questionnaires.armssoftware.com/75527ed2b542"],
  ["Utah Valley University","UT","D1","Men","Soccer","https://www.fieldlevel.com/uvu/soccermen/recruiting"],
  ["Vermont State University Lyndon","VT","D3","Men","Soccer","https://www.fieldlevel.com/lyndonstate/soccermen/recruiting"],
  ["Vermont State University Lyndon","VT","D3","Women","Soccer","https://vtsuhornets.com/sports/2022/7/26/womens-soccer-recruiting-questionnaire.aspx"],
  ["Virginia Tech","VA","D1","Women","Soccer","https://www.fieldlevel.com/vt/soccerwomen/recruiting"],
  ["West Virginia Tech","WV","NAIA","Men","Soccer","https://www.fieldlevel.com/wvutech/soccermen/recruiting"],
  ["West Virginia Tech","WV","NAIA","Women","Soccer","https://www.fieldlevel.com/wvutech/soccerwomen/recruiting"],
  ["Western Iowa Tech Community College","IA","JUCO","Men","Soccer","https://www.fieldlevel.com/anc3xht6/soccermen/recruiting"],
  ["Xavier University of Louisiana","LA","NAIA","Men","Soccer","https://www.fieldlevel.com/fmjv29mn/soccermen/recruiting"],
  ["Alabama A&M University","AL","D1","Women","Softball","https://www.fieldlevel.com/aamu/softball/recruiting"],
  ["Baker University","KS","NAIA","Women","Softball","https://www.fieldlevel.com/bakeru/softball/recruiting"],
  ["Central Connecticut State University","CT","D1","Women","Softball","https://www.fieldlevel.com/ccsu/softball/recruiting"],
  ["College of Southern Nevada","NV","JUCO","Women","Softball","https://www.fieldlevel.com/csn/softball/recruiting"],
  ["Colorado State University Pueblo","CO","D2","Women","Softball","https://questionnaires.armssoftware.com/778f2361e277"],
  ["East Mississippi Community College","MS","JUCO","Women","Softball","https://www.fieldlevel.com/pynjrecy/softball/recruiting"],
  ["Eastern Kentucky University","KY","D1","Women","Softball","https://www.fieldlevel.com/eku/softball/recruiting"],
  ["Iowa State University","IA","D1","Women","Softball","https://questionnaires.armssoftware.com/75bd1185d4f8"],
  ["Middle Georgia State University","GA","NAIA","Women","Softball","https://www.fieldlevel.com/mgc/softball/recruiting"],
  ["Montana State University Billings","MT","D2","Women","Softball","https://www.fieldlevel.com/msubillings/softball/recruiting"],
  ["New York University","NY","D3","Women","Softball","https://questionnaires.armssoftware.com/a400ffae46f6"],
  ["North Dakota State College of Science","ND","JUCO","Women","Softball","https://www.fieldlevel.com/mt7arpn4/softball/recruiting"],
  ["Northwest Nazarene University","ID","D2","Women","Softball","https://www.fieldlevel.com/nnu/softball/recruiting"],
  ["Oakland University","MI","D1","Women","Softball","https://www.fieldlevel.com/oakland/softball/recruiting"],
  ["Ohio Northern University","OH","D3","Women","Softball","https://www.fieldlevel.com/onu/softball/recruiting"],
  ["Oklahoma Wesleyan University","OK","NAIA","Women","Softball","https://www.fieldlevel.com/okwu/softball/recruiting"],
  ["Oregon State University","OR","D1","Women","Softball","https://www.fieldlevel.com/oregonstate/softball/recruiting"],
  ["Ramapo College of New Jersey","NJ","D3","Women","Softball","https://www.fieldlevel.com/ramapo/Softball/recruiting"],
  ["Rhode Island College","RI","D3","Women","Softball","https://www.fieldlevel.com/2jz2czrm/softball/recruiting"],
  ["Seattle University","WA","D1","Women","Softball","https://www.fieldlevel.com/seattleu/softball/recruiting"],
  ["Southern Maine Community College","ME","USCAA","Women","Softball","https://www.fieldlevel.com/gvm8gz8i/softball/recruiting"],
  ["Southern New Hampshire University","NH","D2","Women","Softball","https://questionnaires.armssoftware.com/3f734a933708"],
  ["Southern Virginia University","VA","D3","Women","Softball","https://www.fieldlevel.com/svu/softball/recruiting"],
  ["University of Arizona","AZ","D1","Women","Softball","https://questionnaires.armssoftware.com/8929cb527775"],
  ["University of California, Davis","CA","D1","Women","Softball","https://www.fieldlevel.com/ucdavis/softball/recruiting"],
  ["University of Central Arkansas","AR","D1","Women","Softball","https://www.fieldlevel.com/uca/softball/recruiting"],
  ["University of Delaware","DE","D1","Women","Softball","https://www.fieldlevel.com/udel/softball/recruiting"],
  ["University of Hawaiʻi at Hilo","HI","D2","Women","Softball","https://www.fieldlevel.com/hawaii/softball/recruiting"],
  ["University of Illinois Chicago","IL","D1","Women","Softball","https://www.fieldlevel.com/uic/softball/recruiting"],
  ["University of Maryland, Baltimore County","MD","D1","Women","Softball","https://www.fieldlevel.com/umbc/softball/recruiting"],
  ["University of Massachusetts Amherst","MA","D1","Women","Softball","https://www.fieldlevel.com/umass/softball/recruiting"],
  ["University of Memphis","TN","D1","Women","Softball","https://www.fieldlevel.com/memphis/softball/recruiting"],
  ["University of Minnesota Morris","MN","D3","Women","Softball","https://www.fieldlevel.com/y9j3c9c9/softball/recruiting"],
  ["University of Missouri","MO","D1","Women","Softball","https://questionnaires.armssoftware.com/1b333c8b2889"],
  ["University of Nebraska Omaha","NE","D1","Women","Softball","https://www.fieldlevel.com/unomaha/softball/recruiting"],
  ["University of New Mexico","NM","D1","Women","Softball","https://www.fieldlevel.com/unm/softball/recruiting"],
  ["University of North Carolina Wilmington","NC","D1","Women","Softball","https://www.fieldlevel.com/uncw/softball/recruiting"],
  ["University of Pennsylvania","PA","D1","Women","Softball","https://www.fieldlevel.com/upenn/softball/recruiting"],
  ["University of South Carolina Upstate","SC","D1","Women","Softball","https://www.fieldlevel.com/uscupstate/softball/recruiting"],
  ["University of South Dakota","SD","D1","Women","Softball","https://college.jumpforward.com/questionnaire.aspx?iid=453&sportid=31"],
  ["University of South Florida","FL","D1","Women","Softball","https://www.fieldlevel.com/ke2crij9/softball/recruiting"],
  ["University of Southern Indiana","IN","D1","Women","Softball","https://www.fieldlevel.com/usi/softball/recruiting"],
  ["University of Texas at Tyler","TX","D2","Women","Softball","https://www.fieldlevel.com/rkppqtch/softball/recruiting"],
  ["University of Wisconsin","WI","D1","Women","Softball","https://www.fieldlevel.com/wisconsin/softball/recruiting"],
  ["Utah Valley University","UT","D1","Women","Softball","https://www.fieldlevel.com/uvu/softball/recruiting"],
  ["Vermont State University Lyndon","VT","D3","Women","Softball","https://www.fieldlevel.com/lyndonstate/softball/recruiting"],
  ["West Virginia Tech","WV","NAIA","Women","Softball","https://www.fieldlevel.com/wvutech/softball/recruiting"],
  ["Xavier University of Louisiana","LA","NAIA","Women","Softball","https://www.fieldlevel.com/fmjv29mn/softball/recruiting"],
  ["Baylor University","TX","D1","Men","Tennis","https://questionnaires.armssoftware.com/51b591626fee"],
  ["Baylor University","TX","D1","Women","Tennis","https://questionnaires.armssoftware.com/1e636cdee38b"],
  ["Colorado State University Pueblo","CO","D2","Women","Tennis","https://questionnaires.armssoftware.com/1c859050d552"],
  ["Delaware State University","DE","D1","Women","Tennis","https://questionnaires.armssoftware.com/9a1240910d31?path=wten"],
  ["Duke University","NC","D1","Women","Tennis","https://www.fieldlevel.com/duke/tenniswomen/recruiting"],
  ["Fordham University","NY","D1","Women","Tennis","https://questionnaires.armssoftware.com/80659d3fc6a5"],
  ["Georgia Southwestern State University","GA","D2","Men","Tennis","https://questionnaires.armssoftware.com/0ce8a7804e21"],
  ["Hawaiʻi Pacific University","HI","D2","Women","Tennis","https://questionnaires.armssoftware.com/fdd66fd149cc"],
  ["Massachusetts Institute of Technology","MA","D3","Men","Tennis","https://questionnaires.armssoftware.com/067807003e46"],
  ["Massachusetts Institute of Technology","MA","D3","Women","Tennis","https://questionnaires.armssoftware.com/3a945315c46a"],
  ["Michigan Technological University","MI","D2","Men","Tennis","https://questionnaires.armssoftware.com/30e8c3450869"],
  ["Montana State University","MT","D1","Women","Tennis","https://questionnaires.armssoftware.com/0d317a81ea3f"],
  ["New York University","NY","D3","Men","Tennis","https://questionnaires.armssoftware.com/2f6065d2e25f"],
  ["North Carolina Central University","NC","D1","Men","Tennis","https://questionnaires.armssoftware.com/75ddea380e0b"],
  ["Northern Arizona University","AZ","D1","Men","Tennis","https://questionnaires.armssoftware.com/b0f9c40a80cb"],
  ["Northern Illinois University","IL","D1","Men","Tennis","https://questionnaires.armssoftware.com/9fed50810cea"],
  ["Southeastern Louisiana University","LA","D1","Women","Tennis","https://questionnaires.armssoftware.com/f8f8424e9cb0"],
  ["Southern Illinois University Edwardsville","IL","D1","Women","Tennis","https://questionnaires.armssoftware.com/60acbf3b0238"],
  ["St. Norbert College","WI","D3","Men","Tennis","https://explore.snc.edu/register/m.tennis.rfi"],
  ["St. Norbert College","WI","D3","Women","Tennis","https://explore.snc.edu/register/w.tennis.rfi"],
  ["University of California, Los Angeles","CA","D1","Men","Tennis","https://questionnaires.armssoftware.com/12e7fbe05180"],
  ["University of Connecticut","CT","D1","Women","Tennis","https://questionnaires.armssoftware.com/6d4f9b46d68d"],
  ["University of Hawaiʻi at Mānoa","HI","D1","Men","Tennis","https://questionnaires.armssoftware.com/9c7ba4a2684d"],
  ["University of Maryland, College Park","MD","D1","Women","Tennis","https://questionnaires.armssoftware.com/da23927d069f"],
  ["University of Minnesota Morris","MN","D3","Men","Tennis","https://www.fieldlevel.com/y9j3c9c9/tennismen/recruiting"],
  ["University of Minnesota Morris","MN","D3","Women","Tennis","https://www.fieldlevel.com/y9j3c9c9/tenniswomen/recruiting"],
  ["University of Nebraska Omaha","NE","D1","Men","Tennis","https://questionnaires.armssoftware.com/cf1837ec0f62"],
  ["University of Nevada, Las Vegas","NV","D1","Men","Tennis","https://questionnaires.armssoftware.com/ad91602dd329"],
  ["University of New Mexico","NM","D1","Men","Tennis","https://questionnaires.armssoftware.com/3177fb02ca2e"],
  ["University of Oregon","OR","D1","Women","Tennis","https://goducks.com/form/15"],
  ["University of Rhode Island","RI","D1","Women","Tennis","https://questionnaires.armssoftware.com/5e11965b834f"],
  ["University of South Carolina Upstate","SC","D1","Men","Tennis","https://questionnaires.armssoftware.com/7c3c390f9fb1"],
  ["University of South Carolina Upstate","SC","D1","Women","Tennis","https://questionnaires.armssoftware.com/faa19bf9e0e6"],
  ["University of Southern Indiana","IN","D1","Men","Tennis","https://questionnaires.armssoftware.com/91a808d54133"],
  ["University of Southern Mississippi","MS","D1","Men","Tennis","https://questionnaires.armssoftware.com/12617061d57c"],
  ["University of Tennessee at Chattanooga","TN","D1","Women","Tennis","https://questionnaires.armssoftware.com/631ef4eecdf5"],
  ["University of Utah","UT","D1","Men","Tennis","https://questionnaires.armssoftware.com/aec82e71061a"],
  ["University of Washington","WA","D1","Men","Tennis","https://questionnaires.armssoftware.com/1b9c23153018"],
  ["University of Washington","WA","D1","Women","Tennis","https://gohuskies.com/sports/2017/12/4/uw-wtennis-recruit-questionnaire"],
  ["University of West Alabama","AL","D2","Men","Tennis","https://questionnaires.armssoftware.com/058a55937d66?path=mten"],
  ["University of West Alabama","AL","D2","Women","Tennis","https://questionnaires.armssoftware.com/100cc5bf934a?path=wten"],
  ["University of West Florida","FL","D2","Men","Tennis","https://questionnaires.armssoftware.com/56d9ada8f225"],
  ["Utah Tech University","UT","D1","Women","Tennis","https://questionnaires.armssoftware.com/633fd02e2f01"],
  ["Vermont State University Lyndon","VT","D3","Men","Tennis","https://vtsuhornets.com/sports/2022/7/26/mens-tennis-recruiting-questionnaire.aspx"],
  ["Virginia Tech","VA","D1","Men","Tennis","https://questionnaires.armssoftware.com/eec718334433"],
  ["Washington and Lee University","VA","D3","Women","Tennis","https://questionnaires.armssoftware.com/280718398307"],
  ["Washington University in St. Louis","MO","D3","Men","Tennis","https://washubears.com/sports/2022/8/2/mens-tennis-recruiting-questionnaire.aspx"],
  ["Washington University in St. Louis","MO","D3","Women","Tennis","https://washubears.com/sports/2022/8/2/womens-tennis-recruiting-questionnaire.aspx"],
  ["Wittenberg University","OH","D3","Men","Tennis","https://www.fieldlevel.com/wittenberg/tennismen/recruiting"],
  ["Wittenberg University","OH","D3","Women","Tennis","https://www.fieldlevel.com/wittenberg/tenniswomen/recruiting"],
  ["Arizona State University","AZ","D1","Both","Track & Field","https://questionnaires.armssoftware.com/173d43444532"],
  ["Colorado State University","CO","D1","Women","Track & Field","https://college.jumpforward.com/questionnaire.aspx?iid=1606&sportid=56"],
  ["Eastern New Mexico University","NM","D2","Both","Track & Field","https://questionnaires.armssoftware.com/0b15d0554513"],
  ["Florida State University","FL","D1","Both","Track & Field","https://questionnaires.armssoftware.com/6bb68678fcd1"],
  ["Idaho State University","ID","D1","Both","Track & Field","https://questionnaires.armssoftware.com/3f9f51e50cc7"],
  ["Indiana University Bloomington","IN","D1","Both","Track & Field","https://questionnaires.armssoftware.com/09c3636cf907"],
  ["Kansas State University","KS","D1","Both","Track & Field","https://questionnaires.armssoftware.com/192d07a6fea3"],
  ["Kentucky Wesleyan College","KY","D2","Both","Track & Field","https://questionnaires.armssoftware.com/ec66a53fb746"],
  ["Louisiana State University","LA","D1","Both","Track & Field","https://questionnaires.armssoftware.com/0ac546a5bf3f"],
  ["New Jersey Institute of Technology","NJ","D1","Both","Track & Field","https://questionnaires.armssoftware.com/ed12eb516a9c"],
  ["New York University","NY","D3","Both","Track & Field","https://questionnaires.armssoftware.com/72c321886bd1"],
  ["South Dakota State University","SD","D1","Men","Track & Field","https://questionnaires.armssoftware.com/7808852cca9b"],
  ["Southern Connecticut State University","CT","D2","Men","Track & Field","https://questionnaires.armssoftware.com/bfd16dee13f9"],
  ["University of Alabama","AL","D1","Men","Track & Field","https://questionnaires.armssoftware.com/8192839bdf27"],
  ["University of Alaska Anchorage","AK","D2","Both","Track & Field","https://goseawolves.com/sb_output.aspx?form=9"],
  ["University of California, Los Angeles","CA","D1","Both","Track & Field","https://questionnaires.armssoftware.com/10dfbc77815b"],
  ["University of Central Arkansas","AR","D1","Both","Track & Field","https://questionnaires.armssoftware.com/945dc2639b44"],
  ["University of Delaware","DE","D1","Women","Track & Field","https://questionnaires.armssoftware.com/66172e4afb25"],
  ["University of Georgia","GA","D1","Both","Track & Field","https://questionnaires.armssoftware.com/efb958a7e4ce"],
  ["University of Hawai'i at Mānoa","HI","D1","Women","Track & Field","https://questionnaires.armssoftware.com/0cf03dc86e50"],
  ["University of Illinois Urbana-Champaign","IL","D1","Both","Track & Field","https://questionnaires.armssoftware.com/ee94b0b650db"],
  ["University of Iowa","IA","D1","Both","Track & Field","https://questionnaires.armssoftware.com/d49080741b3e"],
  ["University of Maine","ME","D1","Both","Track & Field","https://questionnaires.armssoftware.com/04e08503c551"],
  ["University of Maryland, College Park","MD","D1","Men","Track & Field","https://questionnaires.armssoftware.com/0f23c8c67469"],
  ["University of Massachusetts Amherst","MA","D1","Women","Track & Field","https://questionnaires.armssoftware.com/9512b1740211"],
  ["University of Michigan","MI","D1","Both","Track & Field","https://questionnaires.armssoftware.com/ddd3c1e8109a"],
  ["University of Minnesota","MN","D1","Both","Track & Field","https://questionnaires.armssoftware.com/82ec9d2859b2"],
  ["University of Mississippi","MS","D1","Both","Track & Field","https://questionnaires.armssoftware.com/a0a22806e53a"],
  ["University of Missouri","MO","D1","Both","Track & Field","https://questionnaires.armssoftware.com/5df5af304de1"],
  ["University of Montana","MT","D1","Women","Track & Field","https://questionnaires.armssoftware.com/cdf78c1ea015"],
  ["University of Nebraska-Lincoln","NE","D1","Both","Track & Field","https://questionnaires.armssoftware.com/169514552f06?path=cross"],
  ["University of Nevada, Las Vegas","NV","D1","Women","Track & Field","https://questionnaires.armssoftware.com/ed7cd3d17320"],
  ["University of New Hampshire","NH","D1","Women","Track & Field","https://questionnaires.armssoftware.com/eb017cd55142"],
  ["University of North Carolina at Chapel Hill","NC","D1","Both","Track & Field","https://questionnaires.armssoftware.com/7c623b73606a"],
  ["University of North Dakota","ND","D1","Both","Track & Field","https://questionnaires.armssoftware.com/c5ee17d79c8c"],
  ["University of Oklahoma","OK","D1","Both","Track & Field","https://questionnaires.armssoftware.com/5d5fb3ed47b1"],
  ["University of Oregon","OR","D1","Men","Track & Field","https://goducks.com/form/12"],
  ["University of Pennsylvania","PA","D1","Women","Track & Field","https://questionnaires.armssoftware.com/7bc46175accb?path=wtrack"],
  ["University of Rhode Island","RI","D1","Women","Track & Field","https://questionnaires.armssoftware.com/33b8965aa1e3"],
  ["University of South Carolina","SC","D1","Both","Track & Field","https://questionnaires.armssoftware.com/84bc1d9bbb6d"],
  ["University of Tennessee","TN","D1","Women","Track & Field","https://questionnaires.armssoftware.com/34f825715f45"],
  ["University of Texas at Austin","TX","D1","Both","Track & Field","https://questionnaires.armssoftware.com/f36d3fe17d38"],
  ["University of Utah","UT","D1","Women","Track & Field","https://questionnaires.armssoftware.com/56a6b87d340b"],
  ["University of Vermont","VT","D1","Women","Track & Field","https://questionnaires.armssoftware.com/d0227476be07"],
  ["University of Washington","WA","D1","Both","Track & Field","https://questionnaires.armssoftware.com/d2b30412ba60"],
  ["University of Wisconsin","WI","D1","Both","Track & Field","https://questionnaires.armssoftware.com/ff7e7f3c2d84"],
  ["University of Wyoming","WY","D1","Women","Track & Field","https://questionnaires.armssoftware.com/b86b97822b05"],
  ["Virginia Tech","VA","D1","Both","Track & Field","https://questionnaires.armssoftware.com/74c75b5593fc"],
  ["West Virginia State University","WV","D2","Both","Track & Field","https://wvsuyellowjackets.com/sb_output.aspx?form=33"],
  ["Xavier University","OH","D1","Both","Track & Field","https://questionnaires.armssoftware.com/5f6b53be3278"],
  ["Arizona State University","AZ","D1","Women","Volleyball","https://questionnaires.armssoftware.com/9f8ef8296f71"],
  ["Arkansas State University","AR","D1","Women","Volleyball","https://www.fieldlevel.com/astate/volleyballwomen/recruiting"],
  ["Colorado Mesa University","CO","D2","Women","Volleyball","https://questionnaires.armssoftware.com/5699288f8ae1"],
  ["Delaware State University","DE","D1","Women","Volleyball","https://questionnaires.armssoftware.com/f8b21dddf370?path=vb"],
  ["Florida State University","FL","D1","Women","Volleyball","https://questionnaires.armssoftware.com/7bc7febf0520"],
  ["Georgia Southern University","GA","D1","Women","Volleyball","https://questionnaires.armssoftware.com/c336723e7da2"],
  ["Hawaiʻi Pacific University","HI","D2","Women","Volleyball","https://questionnaires.armssoftware.com/24da4a8a1956"],
  ["Indiana University Bloomington","IN","D1","Women","Volleyball","https://questionnaires.armssoftware.com/77bc0adb3ddd"],
  ["Kansas State University","KS","D1","Women","Volleyball","https://www.fieldlevel.com/k-state/volleyballwomen/recruiting"],
  ["Mississippi State University","MS","D1","Women","Volleyball","https://hailstate.com/form/18"],
  ["New Jersey Institute of Technology","NJ","D1","Women","Volleyball","https://questionnaires.armssoftware.com/7f9bbf8367f1"],
  ["North Dakota State University","ND","D1","Women","Volleyball","https://questionnaires.armssoftware.com/f3ae860c5e84"],
  ["Northern Illinois University","IL","D1","Women","Volleyball","https://questionnaires.armssoftware.com/14207409138f"],
  ["Ohio State University","OH","D1","Women","Volleyball","https://www.fieldlevel.com/osu/volleyballwomen/recruiting"],
  ["Oregon State University","OR","D1","Women","Volleyball","https://www.fieldlevel.com/oregonstate/volleyballwomen/recruiting"],
  ["South Dakota State University","SD","D1","Women","Volleyball","https://questionnaires.armssoftware.com/308d0714fa28"],
  ["University at Buffalo","NY","D1","Women","Volleyball","https://www.fieldlevel.com/buffalo/volleyballwomen/recruiting"],
  ["University of Alabama","AL","D1","Women","Volleyball","https://questionnaires.armssoftware.com/e7339f20092f"],
  ["University of Alaska Anchorage","AK","D2","Women","Volleyball","https://questionnaires.armssoftware.com/bbdc7f6b0534"],
  ["University of Connecticut","CT","D1","Women","Volleyball","https://questionnaires.armssoftware.com/4495d447fffd"],
  ["University of Idaho","ID","D1","Women","Volleyball","https://college.jumpforward.com/questionnaire.aspx?iid=441&sportid=13"],
  ["University of Iowa","IA","D1","Women","Volleyball","https://questionnaires.armssoftware.com/fc28693fb7b3"],
  ["University of Kentucky","KY","D1","Women","Volleyball","https://www.fieldlevel.com/uky/volleyballwomen/recruiting"],
  ["University of Louisiana at Lafayette","LA","D1","Women","Volleyball","https://questionnaires.armssoftware.com/dc1f22966316"],
  ["University of Maine at Augusta","ME","USCAA","Women","Volleyball","https://www.umamoose.com/information/Recruiting_questionaire/women-s_volleyball_questionnaire"],
  ["University of Maryland, College Park","MD","D1","Women","Volleyball","https://questionnaires.armssoftware.com/446e562694ee"],
  ["University of Massachusetts Amherst","MA","D1","Women","Volleyball","https://www.fieldlevel.com/umass/volleyballwomen/recruiting"],
  ["University of Michigan","MI","D1","Women","Volleyball","https://www.fieldlevel.com/umich/volleyballwomen/recruiting"],
  ["University of Minnesota","MN","D1","Women","Volleyball","https://questionnaires.armssoftware.com/c41edd44b1dd"],
  ["University of Missouri–St. Louis","MO","D2","Women","Volleyball","https://www.fieldlevel.com/umsl/volleyballwomen/recruiting"],
  ["University of Montana","MT","D1","Women","Volleyball","https://www.fieldlevel.com/montana/volleyballwomen/recruiting"],
  ["University of Nebraska Omaha","NE","D1","Women","Volleyball","https://questionnaires.armssoftware.com/b37e0eab1ed3"],
  ["University of Nevada, Las Vegas","NV","D1","Women","Volleyball","https://www.fieldlevel.com/unlv/volleyballwomen/recruiting"],
  ["University of New Hampshire","NH","D1","Women","Volleyball","https://www.fieldlevel.com/crcrdkn9/volleyballwomen/recruiting"],
  ["University of New Mexico","NM","D1","Women","Volleyball","https://www.fieldlevel.com/unm/volleyballwomen/recruiting"],
  ["University of North Carolina at Greensboro","NC","D1","Women","Volleyball","https://questionnaires.armssoftware.com/620417e24325"],
  ["University of Oklahoma","OK","D1","Women","Volleyball","https://www.fieldlevel.com/oklahoma/volleyballwomen/recruiting"],
  ["University of Pennsylvania","PA","D1","Women","Volleyball","https://www.fieldlevel.com/upenn/volleyballwomen/recruiting"],
  ["University of Rhode Island","RI","D1","Women","Volleyball","https://questionnaires.armssoftware.com/f258cf469b3f"],
  ["University of South Carolina","SC","D1","Women","Volleyball","https://questionnaires.armssoftware.com/299212cabf5e"],
  ["University of Southern California","CA","D1","Women","Volleyball","https://questionnaires.armssoftware.com/3af8f01739bb"],
  ["University of Tennessee at Chattanooga","TN","D1","Women","Volleyball","https://questionnaires.armssoftware.com/4b19be345d0a"],
  ["University of Texas at Tyler","TX","D2","Women","Volleyball","https://questionnaires.armssoftware.com/8e352fd84c8f"],
  ["University of Utah","UT","D1","Women","Volleyball","https://www.fieldlevel.com/utah/volleyballwomen/recruiting"],
  ["University of Vermont","VT","D1","Women","Volleyball","https://www.fieldlevel.com/uvm/volleyballwomen/recruiting"],
  ["University of Washington","WA","D1","Women","Volleyball","https://www.fieldlevel.com/washington/volleyballwomen/recruiting"],
  ["University of Wisconsin","WI","D1","Women","Volleyball","https://www.fieldlevel.com/wisconsin/volleyballwomen/recruiting"],
  ["University of Wyoming","WY","D1","Women","Volleyball","https://www.fieldlevel.com/wyoming/volleyballwomen/recruiting"],
  ["Virginia Tech","VA","D1","Women","Volleyball","https://questionnaires.armssoftware.com/3492b8cbe52b"],
  ["West Virginia University","WV","D1","Women","Volleyball","https://www.fieldlevel.com/wvu/volleyballwomen/recruiting"]
];
