// Basketball recruiting questionnaire links — national starter set.
//
// Standalone rather than attached to the College Finder rows: this file names
// schools officially ("University of Alaska Fairbanks") while college-data.js
// uses short names ("Alaska Fairbanks"), and only ~67% reconcile cleanly.
// Rather than risk pointing an athlete at the wrong school's form, these live
// in their own searchable finder keyed by nothing but themselves.
//
// Source: hand-verified list, all rows marked publish=TRUE + Verified,
// updated 2026-08-06. Shape: [school, state, level, gender, url].
// gender is Men | Women | Both. All basketball for now; add a sport column
// if/when other sports are added.

export const QUESTIONNAIRES = [
  ["Allegany College of Maryland", "MD", "JUCO", "Both", "https://acmtrojans.com/sb_output.aspx?form=3"],
  ["Canisius University", "NY", "D1", "Men", "https://gogriffs.com/sb_output.aspx?form=6"],
  ["Central Maine Community College", "ME", "JUCO", "Men", "https://www.cmmustangs.com/information/recruiting/mbkb_recruit"],
  ["Dakota State University", "SD", "NAIA", "Men", "https://dsuathletics.com/sb_output.aspx?form=6"],
  ["Daytona State College", "FL", "JUCO", "Women", "https://dscfalcons.com/sports/wbkb/RecruIt_Questionnaire"],
  ["Delaware State University", "DE", "D1", "Men", "https://questionnaires.armssoftware.com/a8afdc2bf465"],
  ["Dominican University New York", "NY", "D2", "Men", "https://questionnaires.armssoftware.com/b6891d1e43a2"],
  ["East Georgia State College", "GA", "JUCO", "Both", "https://www.ega.edu/athletics/recruit-questionnaire.html"],
  ["Eastern University", "PA", "D3", "Men", "https://goeasterneagles.com/sb_output.aspx?frform=3&path=mbball"],
  ["Florida Institute of Technology", "FL", "D2", "Men", "https://floridatechsports.com/sb_output.aspx?form=40"],
  ["Florida State College at Jacksonville", "FL", "JUCO", "Men", "https://fscjmantarays.com/sports/mbkb/questionnaire"],
  ["Garden City Community College", "KS", "JUCO", "Men", "https://www.gobroncbusters.com/information/mbkb-recuriting"],
  ["Georgia Institute of Technology", "GA", "D1", "Both", "https://ramblinwreck.com/student-athlete-questionnaire/"],
  ["Georgia State University", "GA", "D1", "Men", "https://college.jumpforward.com/questionnaire.aspx?iid=564&sportid=15"],
  ["Georgia State University", "GA", "D1", "Women", "https://georgiastatesports.com/news/2008/11/1/3731625.aspx"],
  ["Grand Rapids Community College", "MI", "JUCO", "Men", "https://grccraiders.com/sb_output.aspx?form=21"],
  ["Hamline University", "MN", "D3", "Men", "https://hamlineathletics.com/sb_output.aspx?frform=2"],
  ["Hawai'i Pacific University", "HI", "D2", "Both", "https://hpusharks.com/sb_output.aspx?form=3"],
  ["IU Indianapolis", "IN", "D1", "Men", "https://questionnaires.armssoftware.com/1e2ec3958a81"],
  ["Illinois Institute of Technology", "IL", "D3", "Both", "https://illinoistechathletics.com/sports/2023/7/13/recruit-form.aspx"],
  ["Illinois State University", "IL", "D1", "Women", "https://college.jumpforward.com/questionnaire.aspx?iid=354&sportid=3"],
  ["Illinois Wesleyan University", "IL", "D3", "Men", "https://www.iwusports.com/sb_output.aspx?frform=1"],
  ["Indiana State University", "IN", "D1", "Men", "https://gosycamores.com/sb_output.aspx?form=14"],
  ["Indiana University Bloomington", "IN", "D1", "Women", "https://college.jumpforward.com/questionnaire.aspx?iid=436&sportid=3"],
  ["Indiana University South Bend", "IN", "NAIA", "Both", "https://iusbtitans.com/sb_output.aspx?form=6"],
  ["Indiana University Southeast", "IN", "NAIA", "Both", "https://iusathletics.com/sb_output.aspx?form=3"],
  ["Kansas City Kansas Community College", "KS", "JUCO", "Men", "https://bluedevils.kckcc.edu/sports/mbkb/recruiting_questionnaire"],
  ["Kentucky State University", "KY", "D2", "Both", "https://ksuthorobreds.com/sb_output.aspx?form=3"],
  ["Lake Michigan College", "MI", "JUCO", "Men", "https://redhawks.lakemichigancollege.edu/sports/mbkb/Men-s_basketball_recruit_form"],
  ["Louisiana Tech University", "LA", "D1", "Women", "https://latechsports.com/sports/2018/7/20/ot-recruiting-questionnaires-html"],
  ["Maine Maritime Academy", "ME", "D3", "Men", "https://questionnaires.armssoftware.com/5f0f295037b5"],
  ["Massachusetts College of Liberal Arts", "MA", "D3", "Men", "https://athletics.mcla.edu/sports/mbkb/Recruit_Me"],
  ["Massachusetts Institute of Technology", "MA", "D3", "Men", "https://questionnaires.armssoftware.com/307fecfb9396"],
  ["Mercy University", "NY", "D2", "Both", "https://mercyathletics.com/sb_output.aspx?form=7"],
  ["Michigan Technological University", "MI", "D2", "Men", "https://questionnaires.armssoftware.com/1f0f9b481572"],
  ["Minnesota State University Mankato", "MN", "D2", "Men", "https://questionnaires.armssoftware.com/6b36740adf92"],
  ["Mississippi State University", "MS", "D1", "Men", "https://hailstate.com/form/9"],
  ["Mississippi State University", "MS", "D1", "Women", "https://hailstate.com/form/2042"],
  ["Missouri Southern State University", "MO", "D2", "Men", "https://questionnaires.armssoftware.com/3ed47a00a1b6"],
  ["Montana State University", "MT", "D1", "Men", "https://questionnaires.armssoftware.com/9f932dabdd0b"],
  ["Montana State University Billings", "MT", "D2", "Men", "https://msubsports.com/sb_output.aspx?form=18"],
  ["Montana State University Northern", "MT", "NAIA", "Both", "https://golightsgo.com/sb_output.aspx?form=3"],
  ["New Jersey Institute of Technology", "NJ", "D1", "Men", "https://questionnaires.armssoftware.com/3cb1c79fc8d0"],
  ["New Mexico State University", "NM", "D1", "Men", "https://nmstatesports.com/sb_output.aspx?form=22"],
  ["North Carolina State University", "NC", "D1", "Both", "https://gopack.com/sports/2015/4/27/GEN_20140101185"],
  ["North Carolina Wesleyan University", "NC", "D3", "Both", "https://ncwsports.com/sports/2024/7/19/prospective-student-athlete-questionnaire-forms.aspx"],
  ["North Dakota State University", "ND", "D1", "Men", "https://questionnaires.armssoftware.com/d9b8c21c0ead"],
  ["Northern Illinois University", "IL", "D1", "Men", "https://questionnaires.armssoftware.com/9accef2bda60"],
  ["Northern Oklahoma College", "OK", "JUCO", "Both", "https://www.nocmavs.com/recruits"],
  ["Ohio Christian University", "OH", "NAIA", "Both", "https://ocutrailblazers.com/sports/2023/9/13/recruiting-questionnaires.aspx"],
  ["Regis College", "MA", "D3", "Men", "https://www.goregispride.com/sports/mbkb/Recruit_Questionnaire"],
  ["Rhodes College", "TN", "D3", "Men", "https://rhodeslynx.com/sb_output.aspx?form=6&path=mbball"],
  ["Rowan College of South Jersey", "NJ", "JUCO", "Both", "https://www.dukesathletics.com/Recruits/questionnaire"],
  ["South Carolina State University", "SC", "D1", "Men", "https://my.armssoftware.com/arms/public/questionnaire/d428372a19c3"],
  ["South Carolina State University", "SC", "D1", "Women", "https://my.armssoftware.com/arms/public/questionnaire/4cf99266ad6f"],
  ["Southeast Missouri State University", "MO", "D1", "Men", "https://college.jumpforward.com/questionnaire.aspx?iid=315&sportid=15"],
  ["Southeastern Louisiana University", "LA", "D1", "Men", "https://questionnaires.armssoftware.com/080d49de4a1a"],
  ["Southern Arkansas University", "AR", "D2", "Men", "https://muleriderathletics.com/sb_output.aspx?form=10"],
  ["Southern New Hampshire University", "NH", "D2", "Both", "https://snhupenmen.com/sports/2021/5/5/information-PSA-questionnaires-index"],
  ["Tennessee Technological University", "TN", "D1", "Both", "https://www.ttusports.com/be_a_golden_eagle/questionnaire_page"],
  ["Texas A&M University", "TX", "D1", "Both", "https://12thman.com/news/2011/08/04/prospective-athlete-questionnaire"],
  ["Texas Wesleyan University", "TX", "NAIA", "Men", "https://ramsports.net/sb_output.aspx?form=7"],
  ["Thomas Jefferson University", "PA", "D2", "Men", "https://jeffersonrams.com/sb_output.aspx?form=7"],
  ["Union College", "NY", "D3", "Men", "https://questionnaires.armssoftware.com/1d274cb1dc08"],
  ["University of Alabama in Huntsville", "AL", "D2", "Men", "https://uahchargers.com/sb_output.aspx?form=5"],
  ["University of Alaska Fairbanks", "AK", "D2", "Men", "https://alaskananooks.com/sb_output.aspx?form=5"],
  ["University of Alaska Fairbanks", "AK", "D2", "Women", "https://questionnaires.armssoftware.com/428bd553cc26"],
  ["University of Arkansas at Monticello", "AR", "D2", "Men", "https://www.uamsports.com/sb_output.aspx?form=27"],
  ["University of Arkansas at Pine Bluff", "AR", "D1", "Both", "https://uapblionsroar.com/sb_output.aspx?form=1"],
  ["University of Central Arkansas", "AR", "D1", "Men", "https://questionnaires.armssoftware.com/f3520c867103"],
  ["University of Central Florida", "FL", "D1", "Men", "https://college.jumpforward.com/questionnaire.aspx?iid=382&path=mbball&sportid=15"],
  ["University of Central Oklahoma", "OK", "D2", "Men", "https://questionnaires.armssoftware.com/ba4f9cb5c69b"],
  ["University of Connecticut", "CT", "D1", "Both", "https://uconnhuskies.com/form/3"],
  ["University of Delaware", "DE", "D1", "Both", "https://www1.udel.edu/forms/sportsinfo/"],
  ["University of Hawai'i at Hilo", "HI", "D2", "Men", "https://questionnaires.armssoftware.com/3a40af83cb1a"],
  ["University of Kansas", "KS", "D1", "Women", "https://questionnaires.armssoftware.com/e27bc4305342"],
  ["University of Kentucky", "KY", "D1", "Both", "https://ukathletics.com/recruits/"],
  ["University of Louisiana Monroe", "LA", "D1", "Men", "https://ulmwarhawks.com/sb_output.aspx?form=6"],
  ["University of Maine at Augusta", "ME", "USCAA", "Both", "https://www.umamoose.com/information/Recruiting_questionaire/basketball_questionnaire"],
  ["University of Maine at Farmington", "ME", "D3", "Men", "https://goumfbeavers.com/sports/2022/5/9/information-forms-recruiting-mens-basketball.aspx"],
  ["University of Maryland, College Park", "MD", "D1", "Both", "https://umterps.com/form/5"],
  ["University of Maryland, College Park", "MD", "D1", "Men", "https://questionnaires.armssoftware.com/637b2b6f576e"],
  ["University of Massachusetts Amherst", "MA", "D1", "Both", "https://umassathletics.com/form/3"],
  ["University of Massachusetts Boston", "MA", "D3", "Men", "https://beaconsathletics.com/sb_output.aspx?form=9"],
  ["University of Michigan-Dearborn", "MI", "NAIA", "Both", "https://athletics.umdearborn.edu/information/recruiting"],
  ["University of Minnesota Crookston", "MN", "D2", "Men", "https://questionnaires.armssoftware.com/5834ab4b585d"],
  ["University of Minnesota Morris", "MN", "NAIA", "Both", "https://admissions.morris.umn.edu/register/RecruitQuestionnaire"],
  ["University of Nebraska at Kearney", "NE", "D2", "Both", "https://lopers.com/sb_output.aspx?form=4"],
  ["University of Nebraska-Lincoln", "NE", "D1", "Men", "https://questionnaires.armssoftware.com/e6b75ca567a7"],
  ["University of Nevada, Reno", "NV", "D1", "Both", "https://nevadawolfpack.com/sb_output.aspx?form=6"],
  ["University of Nevada, Reno", "NV", "D1", "Women", "https://questionnaires.armssoftware.com/3f419f551a8e"],
  ["University of New England", "ME", "D3", "Men", "https://athletics.une.edu/sb_output.aspx?form=29&path=mbball"],
  ["University of New Hampshire", "NH", "D1", "Both", "https://unhwildcats.com/sports/2020/6/19/prospective-student-athlete-questionnaires"],
  ["University of New Hampshire", "NH", "D1", "Men", "https://questionnaires.armssoftware.com/113c1085775c"],
  ["University of North Carolina Asheville", "NC", "D1", "Men", "https://questionnaires.armssoftware.com/ae7cd96f3678"],
  ["University of Northern Iowa", "IA", "D1", "Men", "https://college.jumpforward.com/questionnaire.aspx?iid=537&sportid=15"],
  ["University of Northwestern Ohio", "OH", "NAIA", "Both", "https://www.unoh.edu/athletics/recruit-questionnaire/"],
  ["University of Rhode Island", "RI", "D1", "Both", "https://gorhody.com/sports/2020/6/9/information-psa-questionnaires.aspx"],
  ["University of Rhode Island", "RI", "D1", "Women", "https://questionnaires.armssoftware.com/58324baf0ee4"],
  ["University of South Alabama", "AL", "D1", "Women", "https://questionnaires.armssoftware.com/c83498187260"],
  ["University of South Carolina", "SC", "D1", "Both", "https://gamecocksonline.com/news/2018/06/21/ot-recruiting-questionnaires-html/"],
  ["University of South Carolina Aiken", "SC", "D2", "Both", "https://pacersports.com/sb_output.aspx?form=3"],
  ["University of South Dakota", "SD", "D1", "Men", "https://college.jumpforward.com/questionnaire.aspx?iid=453&sportid=15"],
  ["University of Texas at Dallas", "TX", "D3", "Both", "https://utdcomets.com/sb_output.aspx?form=3"],
  ["University of Texas at Dallas", "TX", "D3", "Men", "https://questionnaires.armssoftware.com/bcc3263f7612"],
  ["University of Texas at San Antonio", "TX", "D1", "Both", "https://goutsa.com/prospective-student-athletes-questionnaires"],
  ["University of Vermont", "VT", "D1", "Men", "https://questionnaires.armssoftware.com/a4faa3edaa60"],
  ["University of Wisconsin-Green Bay", "WI", "D1", "Men", "https://greenbayphoenix.com/sb_output.aspx?form=5"],
  ["Virginia Polytechnic Institute and State University", "VA", "D1", "Men", "https://college.jumpforward.com/questionnaire.aspx?iid=472&sportid=15"],
  ["WVU Potomac State College", "WV", "JUCO", "Men", "https://www.potomacstatesports.com/recruits/mbasketball-recruits"],
  ["Wagner College", "NY", "D1", "Men", "https://wagnerathletics.com/sb_output.aspx?form=26"],
  ["Western Connecticut State University", "CT", "D3", "Men", "https://westconnathletics.com/sb_output.aspx?form=18"],
  ["Western Illinois University", "IL", "D1", "Both", "https://goleathernecks.com/sb_output.aspx?form=3"],
  ["Western Oklahoma State College", "OK", "JUCO", "Men", "https://pioneers.wosc.edu/sports/mbkb/recruiting_form"],
  ["Xavier University of Louisiana", "LA", "NAIA", "Both", "https://xulagold.com/sports/2019/3/20/recruiting-questionnaires"]
];
